### ISSUE TITLE
Noget du har glemt at fjerne?

### ISSUE THREAD

**Issue by klementj** [jesp6763/Proveeksamen-V31-F2018-3-KLJO#2]
https://github.com/jesp6763/Proveeksamen-V31-F2018-3-KLJO/blob/d3aadd5159a167e5dfe5ce1461fa82726768eb74/js/View/MoviesPage.js#L36

Har du glemt at fjerne disse to linjer? :)

**Comment by jesp6763** [comment]
Hmm, troede faktisk de var nødvendige, men prøvede lige at slette dem og det virker stadig. Så tak for det, har slettet dem nu :-)
